### ISSUE TITLE
Samsung Galaxy S4 error

### ISSUE THREAD

**Issue by PS-s** [lighthouse3d/AndroidGL#3]
Crash with :

12-18 11:41:37.441 1492-1649/com.example.arf.opengljava E/AndroidRuntime: FATAL EXCEPTION: GLThread 14520
                                                                          Process: com.example.arf.opengljava, PID: 1492
                                                                          java.lang.IllegalArgumentException: eglChooseConfig failed
                                                                              at android.opengl.GLSurfaceView$BaseConfigChooser.chooseConfig(GLSurfaceView.java:861)
                                                                              at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1032)
                                                                              at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1409)
                                                                              at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)

**Comment by Nau3D** [comment]
Hi,
The demo is written as requiring GL ES 3.0. From the message I would say that it is not supported on that phone. Can you verify your GL ES? 

Best Regards,
Antonio

**Comment by PS-s** [comment]
Hello.
https://developer.android.com:
OpenGL ES 1.0 and 1.1 - This API specification is supported by Android 1.0 and higher.
OpenGL ES 2.0 - This API specification is supported by Android 2.2 (API level 8) and higher.
OpenGL ES 3.0 - This API specification is supported by Android 4.3 (API level 18) and higher.
OpenGL ES 3.1 - This API specification is supported by Android 5.0 (API level 21) and higher.

And version of my phone is  Android 5.0.
But i have crash.

**Comment by Nau3D** [comment]
Hi, sorry for the late reply. 

In the Android world there are differences between ACTUAL supported using the same version of Android. There are a few apps that will tell you if you really have support for OpenGL 3.0. From your error message it doesn't seem like it.

Best Regards,
Antonio
